import type { Vec2 } from '../../types'

/**
 * Generate a jagged lightning bolt path from `start` to `end`.
 * Uses recursive midpoint displacement for a natural look.
 */
export function generateLightningBolt(
  start: Vec2,
  end: Vec2,
  displacement: number,
  depth: number,
  rng: () => number = Math.random,
): Vec2[] {
  if (depth === 0 || displacement < 2) {
    return [start, end]
  }
  const midX = (start.x + end.x) * 0.5
  const midY = (start.y + end.y) * 0.5
  const angle = Math.atan2(end.y - start.y, end.x - start.x) + Math.PI / 2
  const offset = displacement * (rng() * 2 - 1)
  const mid: Vec2 = {
    x: midX + Math.cos(angle) * offset,
    y: midY + Math.sin(angle) * offset,
  }
  const left = generateLightningBolt(start, mid, displacement * 0.5, depth - 1, rng)
  const right = generateLightningBolt(mid, end, displacement * 0.5, depth - 1, rng)
  return [...left.slice(0, -1), ...right]
}

/**
 * Draw a lightning bolt on the canvas.
 * `bolt` is the path generated by generateLightningBolt.
 * `age` is time elapsed since the bolt appeared (ms).
 * `duration` is total bolt display duration (ms).
 */
export function drawLightningBolt(
  ctx: CanvasRenderingContext2D,
  bolt: Vec2[],
  age: number,
  duration: number,
): void {
  if (bolt.length < 2) return
  const alpha = Math.max(0, 1 - age / duration)
  if (alpha <= 0) return

  ctx.save()
  ctx.globalAlpha = alpha

  // Outer glow (wide, dim, blue-white)
  ctx.strokeStyle = 'rgba(180,210,255,0.35)'
  ctx.lineWidth = 10
  ctx.lineCap = 'round'
  ctx.lineJoin = 'round'
  ctx.beginPath()
  ctx.moveTo(bolt[0].x, bolt[0].y)
  for (let i = 1; i < bolt.length; i++) ctx.lineTo(bolt[i].x, bolt[i].y)
  ctx.stroke()

  // Mid layer (medium, white-blue)
  ctx.strokeStyle = 'rgba(200,220,255,0.6)'
  ctx.lineWidth = 4
  ctx.beginPath()
  ctx.moveTo(bolt[0].x, bolt[0].y)
  for (let i = 1; i < bolt.length; i++) ctx.lineTo(bolt[i].x, bolt[i].y)
  ctx.stroke()

  // Core (narrow, bright white-yellow)
  ctx.strokeStyle = 'rgba(255,255,240,0.95)'
  ctx.lineWidth = 1.5
  ctx.beginPath()
  ctx.moveTo(bolt[0].x, bolt[0].y)
  for (let i = 1; i < bolt.length; i++) ctx.lineTo(bolt[i].x, bolt[i].y)
  ctx.stroke()

  ctx.restore()
}
