export const CONFIG = {
  canvas: { width: 1280, height: 720 },
  hand: { fingertipLandmark: 8, maxHands: 2 },
  slash: { velocityThreshold: 900, trailLifetimeMs: 160, minSegmentPx: 4 },
  calibration: {
    sampleMs: 3000,
    margin: 0.04,
    defaultBox: { minX: 0.2, minY: 0.2, maxX: 0.8, maxY: 0.8 },
    storageKey: 'fruitFury.reachBox',
  },
  combo: { windowMs: 220, minForBonus: 3, bonusPerExtra: 50 },
  spawn: {
    baseIntervalMs: 1100,
    minIntervalMs: 450,
    rampMs: 60000,
    baseBombChance: 0.07,
    maxBombChance: 0.2,
    launchSpeed: { min: 850, max: 1050 },
    radius: { fruit: 46, bomb: 40 },
  },
  physics: { gravity: 1400 },
  lives: 3,
  points: { fruit: 10 },
  particles: { maxCount: 400, perCut: 14 },
  highScoreKey: 'fruitFury.highScore',
} as const
