export const CONFIG = {
  canvas: { width: 1280, height: 720 },
  hand: { fingertipLandmark: 8, maxHands: 2 },
  slash: { velocityThreshold: 700, trailLifetimeMs: 160, minSegmentPx: 4, smoothing: 0.4 },
  calibration: {
    sampleMs: 3000,
    margin: 0.04,
    defaultBox: { minX: 0, minY: 0, maxX: 1, maxY: 1 },
    storageKey: 'fruitFury.reachBox',
  },
  combo: { windowMs: 220, minForBonus: 3, bonusPerExtra: 50 },
  spawn: {
    baseIntervalMs: 1100,
    minIntervalMs: 450,
    rampMs: 60000,
    baseBombChance: 0.07,
    maxBombChance: 0.2,
    launchSpeed: { min: 1050, max: 1300 },
    radius: { fruit: 46, bomb: 40 },
  },
  physics: { gravity: 1100 },
  lives: 5,
  points: { fruit: 10 },
  particles: { maxCount: 400, perCut: 14 },
  highScoreKey: 'fruitFury.highScore',
} as const
